'use client';
import { Plus, ShieldCheck } from 'lucide-react';
import { useEffect, useState } from 'react';
import DashboardLayout from '@/components/layout/DashboardLayout';
import { useAuth } from '@/context/AuthContext';
import { createFiscalEnrollment, endFiscalEnrollment, listFiscalEnrollments, type FiscalEnrollment } from '@/services/fiscal-enrollments';
const taxes = ['IVA', 'INDUSTRIAL', 'IRT', 'SS'];
const day = (value?: string | null) => value ? value.slice(0, 10) : 'Sem termo';
export default function FiscalEnrollmentsPage() {
 const { user } = useAuth(); const canWrite=['OWNER','ADMIN','ACCOUNTANT'].includes(user?.role ?? '');
 const [items,setItems]=useState<FiscalEnrollment[]>([]); const [error,setError]=useState(''); const [form,setForm]=useState({taxType:'IVA',regime:'GERAL',validFrom:'',validUntil:'',legalReference:''});
 const load=async()=>{try{setItems(await listFiscalEnrollments())}catch{setError('Não foi possível carregar os enquadramentos fiscais.')}}; useEffect(()=>{void load()},[]);
 const create=async(e:React.FormEvent)=>{e.preventDefault(); try {await createFiscalEnrollment({...form,validUntil:form.validUntil||undefined,legalReference:form.legalReference||undefined}); setForm({...form,validFrom:'',validUntil:'',legalReference:''}); await load()}catch(err:any){setError(err?.response?.data?.message||'Não foi possível guardar o enquadramento.')}};
 const end=async(id:string)=>{const validUntil=window.prompt('Data de fim (AAAA-MM-DD):'); if(!validUntil)return; try{await endFiscalEnrollment(id,validUntil);await load()}catch(err:any){setError(err?.response?.data?.message||'Não foi possível encerrar o enquadramento.')}};
 return <DashboardLayout><main className="min-h-full bg-[#f7f9fc] px-4 py-5 sm:px-6 lg:px-8"><div className="mx-auto max-w-6xl"><header className="mb-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-sky-700">Central Fiscal</p><h1 className="mt-1 text-2xl font-extrabold text-slate-900">Enquadramentos fiscais</h1><p className="mt-2 text-sm text-slate-600">Cada imposto possui o seu próprio regime e histórico de vigência. Não existe um regime universal da empresa.</p></header>{error&&<p role="alert" className="mb-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</p>}{canWrite&&<form onSubmit={create} className="mb-6 grid gap-3 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:grid-cols-5"><select value={form.taxType} onChange={e=>setForm({...form,taxType:e.target.value})} className="fd-field">{taxes.map(x=><option key={x}>{x}</option>)}</select><select value={form.regime} onChange={e=>setForm({...form,regime:e.target.value})} className="fd-field"><option>GERAL</option><option>SIMPLIFICADO</option></select><input required type="date" value={form.validFrom} onChange={e=>setForm({...form,validFrom:e.target.value})} className="fd-field"/><input type="date" value={form.validUntil} onChange={e=>setForm({...form,validUntil:e.target.value})} className="fd-field"/><button className="inline-flex items-center justify-center gap-2 rounded-lg bg-sky-700 px-4 py-2 text-sm font-bold text-white"><Plus size={16}/>Adicionar</button></form>}<section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-bold text-slate-900">Histórico</h2></div><div className="divide-y">{items.map(item=><article key={item.id} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold text-slate-900">{item.taxType} · {item.regime}</p><p className="mt-1 text-sm text-slate-600">{day(item.validFrom)} até {day(item.validUntil)} · {item.status}</p>{item.legalReference&&<p className="mt-1 text-xs text-slate-500">{item.legalReference}</p>}</div>{canWrite&&item.status==='ACTIVE'&&<button onClick={()=>void end(item.id)} className="rounded-lg border border-slate-300 px-3 py-2 text-sm font-bold text-slate-700">Encerrar</button>}</article>)}{!items.length&&<div className="p-10 text-center text-sm text-slate-500"><ShieldCheck className="mx-auto mb-3"/>Sem enquadramentos registados.</div>}</div></section></div></main></DashboardLayout>;
}
